// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArHaf7_B2n3eyuqpDzJllV19RFTa5Owkc',
    appId: '1:779432568715:web:1802234a978b9bd086318e',
    messagingSenderId: '779432568715',
    projectId: 'veciapp-606ce',
    authDomain: 'veciapp-606ce.firebaseapp.com',
    storageBucket: 'veciapp-606ce.firebasestorage.app',
    measurementId: 'G-0CTQ5N56TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWlrc5g_A6DMBOrsDUBgJvneQG0t8F8-A',
    appId: '1:779432568715:android:533c8a717492b6dd86318e',
    messagingSenderId: '779432568715',
    projectId: 'veciapp-606ce',
    storageBucket: 'veciapp-606ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLWrII73G4j6C_Tg8XC05uD4HnbUk4iIc',
    appId: '1:779432568715:ios:8ad62943d98225ef86318e',
    messagingSenderId: '779432568715',
    projectId: 'veciapp-606ce',
    storageBucket: 'veciapp-606ce.firebasestorage.app',
    iosBundleId: 'com.example.veciApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLWrII73G4j6C_Tg8XC05uD4HnbUk4iIc',
    appId: '1:779432568715:ios:8ad62943d98225ef86318e',
    messagingSenderId: '779432568715',
    projectId: 'veciapp-606ce',
    storageBucket: 'veciapp-606ce.firebasestorage.app',
    iosBundleId: 'com.example.veciApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArHaf7_B2n3eyuqpDzJllV19RFTa5Owkc',
    appId: '1:779432568715:web:be05c114fbb209a286318e',
    messagingSenderId: '779432568715',
    projectId: 'veciapp-606ce',
    authDomain: 'veciapp-606ce.firebaseapp.com',
    storageBucket: 'veciapp-606ce.firebasestorage.app',
    measurementId: 'G-F2YDET111B',
  );
}
